version: 0.2
# environment_variables:  
#     plaintext:  
#         S3_BUCKET: "s3bucket1"  
phases:  
    install:  
        runtime-versions:  
            nodejs : 14
        commands:  
            - echo Installing source NPM dependencies...  
            - npm init -f
            - npm install
            - npm install --save express serverless-http
            - npm install -g serverless
    build:  
        commands:  
            - serverless deploy --stage dev
            
    post_build:  
         commands:  
            # aws s3 rm s3://${S3_BUCKET} --recursive  
            - pwd  
            - ls -l
            - echo Build completed on `date`
            
artifacts:  
    files:
        - src/index.js
        - src/app.js
        - package.json
        - node_modules/**/* 
